name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Package Spring Boot Application
        run: mvn -B package -DskipTests --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/blinkid-spring-bootapp-0.0.1-SNAPSHOT.jar

      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          wait_for_deployment: false
          application_name: blink-id
          environment_name: Blink-id-env
          version_label: ${{github.SHA}}
          region: us-east-2
          deployment_package: blinkid-spring-bootapp-0.0.1-SNAPSHOT.jar
